version: "3"

services:
  # mongod:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app/
    ports:
      - 8080:8080
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /usr/app/node_modules
  #     - .:/usr/app/
    # command: ["npm", "run", "dev"]
